Q1.Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
import numpy as np

# Create a regular Python list
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array
array_list = np.array([1, 2, 3, 4, 5])

# Print the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


Q2.Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
# Create a regular Python list
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array
array_list = np.array([1, 2, 3, 4, 5])

# Print data types of each element in 'list_'
print("Data types in 'list_':")
for element in list_:
    print(type(element))

# Print data types of each element in 'array_list'
print("\nData types in 'array_list':")
for element in array_list:
    print(type(element))

Data types in 'list_':
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q3.

In [4]:
import numpy as np

# Create a regular Python list
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array with specified data type 'int'
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in 'list_'
print("Data types in 'list_':")
for element in list_:
    print(type(element))

# Print data types of each element in 'array_list'
print("\nData types in 'array_list':")
for element in array_list:
    print(type(element))


Data types in 'list_':
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4

In [6]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
df=num_array

In [10]:
df

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
df.shape

(2, 3)

In [13]:
df.size

6

Q5

In [16]:
zero_matrix = np.zeros((3,3))

In [17]:
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6

In [20]:
diagonal_matrix = np.eye(5)

In [21]:
print(diagonal_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
